export class Usuario {
    login:               string;
    id:                  number;
    node_id:             string;
    avatar_url:          string;
    gravatar_id:         string;
    url:                 string;
    html_url:            string;
    followers_url:       string;
    following_url:       string;
    gists_url:           string;
    starred_url:         string;
    subscriptions_url:   string;
    organizations_url:   string;
    repos_url:           string;
    events_url:          string;
    received_events_url: string;
    type:                string;
    site_admin:          boolean;
    name:                null;
    company:             null;
    blog:                string;
    location:            null;
    email:               null;
    hireable:            null;
    bio:                 null;
    twitter_username:    null;
    public_repos:        number;
    public_gists:        number;
    followers:           number;
    following:           number;
    created_at:          Date;
    updated_at:          Date;

    constructor(){
    this.login               = '';
    this.id                  = 0;
    this.node_id            = '';
    this.avatar_url          = '';
    this.gravatar_id        = '';
    this.url                 = '';
    this.html_url           = '';
    this.followers_url      = '';
    this.following_url      = '';
    this.gists_url           = '';
    this.starred_url         = '';
    this.subscriptions_url  = '';
    this.organizations_url   = '';
    this.repos_url           = '';
    this.events_url          = '';
    this.received_events_url = '';
    this.type                = '';
    this.site_admin          = false;
    this.name                = null;
    this.company             = null;
    this.blog                = '';
    this.location            = null;
    this.email               = null;
    this.hireable            = null;
    this.bio                 = null;
    this.twitter_username    = null;
    this.public_repos        = 0;
    this.public_gists        = 0;
    this.followers           = 0;
    this.following           = 0;
    this.created_at          =  new Date();
    this.updated_at = new Date();    
    }
}
